In [2]:
from IPython.display import Image
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

# 컬럼(columns) 설명
- survivied: 생존여부 (1: 생존, 0: 사망)
- pclass: 좌석 등급 (1등급, 2등급, 3등급)
- sex: 성별
- age: 나이
- sibsp: 형제 + 배우자 수
- parch: 부모 + 자녀 수
- fare: 좌석 요금
- embarked: 탑승 항구 (S, C, Q)
- class: pclass와 동일
- who: 남자(man), 여자(woman), 아이(child)
- adult_male: 성인 남자 여부
- deck: 데크 번호 (알파벳 + 숫자 혼용)
- embark_town: 탑승 항구 이름
- alive: 생존여부 (yes, no)
- alone: 혼자 탑승 여부

In [5]:
# apply
def transform_who(x):
  if x == 'man':
    return '남자'
  elif x == 'woman':
    return '여자'
  else:
    return '아이'

df['who'].apply(transform_who)

0      남자
1      여자
2      여자
3      여자
4      남자
       ..
886    남자
887    여자
888    여자
889    남자
890    남자
Name: who, Length: 891, dtype: object

In [6]:
def transform_who(x):
  return x['fare'] / x['age']

df.apply(transform_who, axis=1)

0      0.329545
1      1.875876
2      0.304808
3      1.517143
4      0.230000
         ...
886    0.481481
887    1.578947
888         NaN
889    1.153846
890    0.242188
Length: 891, dtype: float64

In [7]:
df['survived'].value_counts()

0    549
1    342
Name: survived, dtype: int64

In [8]:
df['survived'].apply(lambda x: '생존' if x == 1 else '사망')

0      사망
1      생존
2      생존
3      생존
4      사망
       ..
886    사망
887    생존
888    사망
889    생존
890    사망
Name: survived, Length: 891, dtype: object

In [9]:
df['survived'].apply(lambda x: '생존' if x == 1 else '사망').value_counts()

사망    549
생존    342
Name: survived, dtype: int64

In [10]:
df.groupby('sex').mean()

C:\Users\milman2\AppData\Local\Temp\ipykernel_9252\3838006174.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('sex').mean()

,survived,pclass,age,sibsp,parch,fare,adult_male,alone
sex,,,,,,,,
female,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818,0.000000,0.401274
male,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893,0.930676,0.712305

In [11]:
df.groupby(['sex', 'pclass']).mean()

C:\Users\milman2\AppData\Local\Temp\ipykernel_9252\4217167109.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['sex', 'pclass']).mean()

               survived        age     sibsp     parch        fare  \
sex    pclass
female 1       0.968085  34.611765  0.553191  0.457447  106.125798
       2       0.921053  28.722973  0.486842  0.605263   21.970121
       3       0.500000  21.750000  0.895833  0.798611   16.118810
male   1       0.368852  41.281386  0.311475  0.278689   67.226127
       2       0.157407  30.740707  0.342593  0.222222   19.741782
       3       0.135447  26.507589  0.498559  0.224784   12.661633

               adult_male     alone
sex    pclass
female 1         0.000000  0.361702
       2         0.000000  0.421053
       3         0.000000  0.416667
male   1         0.975410  0.614754
       2         0.916667  0.666667
       3         0.919308  0.760807

In [12]:
df.groupby(['sex', 'pclass'])['survived'].mean()

sex     pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: survived, dtype: float64

In [13]:
pd.DataFrame(df.groupby(['sex', 'pclass'])['survived'].mean())

               survived
sex    pclass
female 1       0.968085
       2       0.921053
       3       0.500000
male   1       0.368852
       2       0.157407
       3       0.135447

In [14]:
df.groupby(['sex', 'pclass'])[['survived']].mean()

               survived
sex    pclass
female 1       0.968085
       2       0.921053
       3       0.500000
male   1       0.368852
       2       0.157407
       3       0.135447

In [15]:
df.groupby(['sex', 'pclass'])['survived'].mean().reset_index()

      sex  pclass  survived
0  female       1  0.968085
1  female       2  0.921053
2  female       3  0.500000
3    male       1  0.368852
4    male       2  0.157407
5    male       3  0.135447

In [16]:
df.groupby(['sex', 'pclass'])[['survived', 'age']].mean()

               survived        age
sex    pclass
female 1       0.968085  34.611765
       2       0.921053  28.722973
       3       0.500000  21.750000
male   1       0.368852  41.281386
       2       0.157407  30.740707
       3       0.135447  26.507589

In [17]:
# 성별, 좌석등급 별 통계
df.groupby(['sex', 'pclass'])[['survived', 'age']].agg(['mean', 'sum'])

               survived            age
                   mean sum       mean      sum
sex    pclass
female 1       0.968085  91  34.611765  2942.00
       2       0.921053  70  28.722973  2125.50
       3       0.500000  72  21.750000  2218.50
male   1       0.368852  45  41.281386  4169.42
       2       0.157407  17  30.740707  3043.33
       3       0.135447  47  26.507589  6706.42

In [18]:
df.pivot_table(index='who', values='survived')
# By default, the pivot_table calculates the mean, so the output values are the averages.

       survived
who
child  0.590361
man    0.163873
woman  0.756458

In [20]:
df.pivot_table(columns='who', values='survived')

who          child       man     woman
survived  0.590361  0.163873  0.756458

In [21]:
df.pivot_table(index=['who', 'pclass'], values='survived')

              survived
who   pclass
child 1       0.833333
      2       1.000000
      3       0.431034
man   1       0.352941
      2       0.080808
      3       0.119122
woman 1       0.978022
      2       0.909091
      3       0.491228

In [22]:
df.pivot_table(index='who', columns='pclass', values='survived')

pclass         1         2         3
who
child   0.833333  1.000000  0.431034
man     0.352941  0.080808  0.119122
woman   0.978022  0.909091  0.491228

In [23]:
df.pivot_table(index='who', columns='pclass', values='survived', aggfunc=['sum', 'mean'])

       sum              mean
pclass   1   2   3         1         2         3
who
child    5  19  25  0.833333  1.000000  0.431034
man     42   8  38  0.352941  0.080808  0.119122
woman   89  60  56  0.978022  0.909091  0.491228