In [1]:
from IPython.display import Image
import numpy as np
import pandas as pd
import seaborn as sns
import warnings

# warning 무시
warnings.filterwarnings('ignore')

# e notation 표현 방식 변경
pd.options.display.float_format = '{:.2f}'.format

# 모든 컬럼 표시
pd.set_option('display.max_columns', None)

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.00,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.00,1,0,71.28,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.00,0,0,7.92,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.00,1,0,53.10,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.00,0,0,8.05,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df1 = df.copy()
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.00,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.00,1,0,71.28,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.00,0,0,7.92,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.00,1,0,53.10,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.00,0,0,8.05,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# 새로운 컬럼 추가
df1['VIP'] = True
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.00,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False,True
1,1,1,female,38.00,1,0,71.28,C,First,woman,False,C,Cherbourg,yes,False,True
2,1,3,female,26.00,0,0,7.92,S,Third,woman,False,NaN,Southampton,yes,True,True
3,1,1,female,35.00,1,0,53.10,S,First,woman,False,C,Southampton,yes,False,True
4,0,3,male,35.00,0,0,8.05,S,Third,man,True,NaN,Southampton,no,True,True

In [5]:
# insert(컬럼인덱스, 컬럼명, 값)
df1.insert(5, 'RICH', df1['fare'] > 100)
df1.head()

,survived,pclass,sex,age,sibsp,RICH,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.00,1,False,0,7.25,S,Third,man,True,NaN,Southampton,no,False,True
1,1,1,female,38.00,1,False,0,71.28,C,First,woman,False,C,Cherbourg,yes,False,True
2,1,3,female,26.00,0,False,0,7.92,S,Third,woman,False,NaN,Southampton,yes,True,True
3,1,1,female,35.00,1,False,0,53.10,S,First,woman,False,C,Southampton,yes,False,True
4,0,3,male,35.00,0,False,0,8.05,S,Third,man,True,NaN,Southampton,no,True,True

In [7]:
# 행 삭제
#df1.drop(1)
#df1.drop(np.arange(10))
df1.drop([1, 3, 5, 7, 9])

,survived,pclass,sex,age,sibsp,RICH,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.00,1,False,0,7.25,S,Third,man,True,NaN,Southampton,no,False,True
2,1,3,female,26.00,0,False,0,7.92,S,Third,woman,False,NaN,Southampton,yes,True,True
4,0,3,male,35.00,0,False,0,8.05,S,Third,man,True,NaN,Southampton,no,True,True
6,0,1,male,54.00,0,False,0,51.86,S,First,man,True,E,Southampton,no,True,True
8,1,3,female,27.00,0,False,2,11.13,S,Third,woman,False,NaN,Southampton,yes,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.00,0,False,0,13.00,S,Second,man,True,NaN,Southampton,no,True,True
887,1,1,female,19.00,0,False,0,30.00,S,First,woman,False,B,Southampton,yes,True,True
888,0,3,female,NaN,1,False,2,23.45,S,Third,woman,False,NaN,Southampton,no,False,True
889,1,1,male,26.00,0,False,0,30.00,C,First,man,True,C,Cherbourg,yes,True,True
890,0,3,male,32.00,0,False,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True,True

In [10]:
# 열 삭제
#df1.drop('class', axis=1).head()
df1.drop(['who', 'deck', 'alive'], axis=1)
#df1.drop(['who', 'deck', 'alive'], axis=1, inplace=True)

,survived,pclass,sex,age,sibsp,RICH,parch,fare,embarked,class,adult_male,embark_town,alone,VIP
0,0,3,male,22.00,1,False,0,7.25,S,Third,True,Southampton,False,True
1,1,1,female,38.00,1,False,0,71.28,C,First,False,Cherbourg,False,True
2,1,3,female,26.00,0,False,0,7.92,S,Third,False,Southampton,True,True
3,1,1,female,35.00,1,False,0,53.10,S,First,False,Southampton,False,True
4,0,3,male,35.00,0,False,0,8.05,S,Third,True,Southampton,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.00,0,False,0,13.00,S,Second,True,Southampton,True,True
887,1,1,female,19.00,0,False,0,30.00,S,First,False,Southampton,True,True
888,0,3,female,NaN,1,False,2,23.45,S,Third,False,Southampton,False,True
889,1,1,male,26.00,0,False,0,30.00,C,First,True,Cherbourg,True,True
890,0,3,male,32.00,0,False,0,7.75,Q,Third,True,Queenstown,True,True

In [11]:
df1 = df.copy()
df1['family'] = df1['sibsp'] + df1['parch']
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family
0,0,3,male,22.00,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False,1
1,1,1,female,38.00,1,0,71.28,C,First,woman,False,C,Cherbourg,yes,False,1
2,1,3,female,26.00,0,0,7.92,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,35.00,1,0,53.10,S,First,woman,False,C,Southampton,yes,False,1
4,0,3,male,35.00,0,0,8.05,S,Third,man,True,NaN,Southampton,no,True,0

In [12]:
df1.loc[df1['age'].isnull(), 'deck':].head()

   deck  embark_town alive  alone  family
5   NaN   Queenstown    no   True       0
17  NaN  Southampton   yes   True       0
19  NaN    Cherbourg   yes   True       0
26  NaN    Cherbourg    no   True       0
28  NaN   Queenstown   yes   True       0

In [13]:
df1['who'].astype('category').head()

0      man
1    woman
2    woman
3    woman
4      man
Name: who, dtype: category
Categories (3, object): ['child', 'man', 'woman']

In [15]:
df1['who'] = df1['who'].astype('category')
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    category
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
 15  family       891 non-null    int64
dtypes: bool(2), category(3), float64(2), int64(5), object(4)
memory usage: 81.7+ KB

In [16]:
df1['who'].cat.categories

Index(['child', 'man', 'woman'], dtype='object')

In [17]:
df1['who'].cat.categories = ['아이', '남자', '여자']
df1['who'].value_counts()

남자    537
여자    271
아이     83
Name: who, dtype: int64

In [18]:
df1['who'].cat

In [19]:
df2 = pd.read_csv('data/seoul_bicycle.csv')
df2.head()

         대여일자  대여시간  대여소번호 대여구분코드 성별 연령대코드  이용건수    운동량   탄소량    이동거리  사용시간
0  2021-06-01     0   3541    정기권  F  ~10대     1   0.00  0.00    0.00     8
1  2021-06-01     0    765    정기권  F  ~10대     1  27.21  0.35 1526.81    19
2  2021-06-01     0   2637    정기권  F  ~10대     1  41.40  0.37 1608.56    18
3  2021-06-01     0   2919    정기권  F  ~10대     1   0.00  0.00    0.00    75
4  2021-06-01     0    549    정기권  F  ~10대     1  13.04  0.17  731.55     6

In [21]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 678950 entries, 0 to 678949
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   대여일자    678950 non-null  object
 1   대여시간    678950 non-null  int64
 2   대여소번호   678950 non-null  int64
 3   대여구분코드  678950 non-null  object
 4   성별      678950 non-null  object
 5   연령대코드   678950 non-null  object
 6   이용건수    678950 non-null  int64
 7   운동량     678950 non-null  object
 8   탄소량     678950 non-null  object
 9   이동거리    678950 non-null  float64
 10  사용시간    678950 non-null  int64
dtypes: float64(1), int64(4), object(6)
memory usage: 57.0+ MB

In [22]:
pd.to_datetime(df2['대여일자'])

0        2021-06-01
1        2021-06-01
2        2021-06-01
3        2021-06-01
4        2021-06-01
            ...
678945   2021-06-14
678946   2021-06-14
678947   2021-06-14
678948   2021-06-14
678949   2021-06-14
Name: 대여일자, Length: 678950, dtype: datetime64[ns]

In [23]:
df2['대여일자'] = pd.to_datetime(df2['대여일자'])
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 678950 entries, 0 to 678949
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   대여일자    678950 non-null  datetime64[ns]
 1   대여시간    678950 non-null  int64
 2   대여소번호   678950 non-null  int64
 3   대여구분코드  678950 non-null  object
 4   성별      678950 non-null  object
 5   연령대코드   678950 non-null  object
 6   이용건수    678950 non-null  int64
 7   운동량     678950 non-null  object
 8   탄소량     678950 non-null  object
 9   이동거리    678950 non-null  float64
 10  사용시간    678950 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 57.0+ MB

In [24]:
df2['대여일자'].dt.year

0         2021
1         2021
2         2021
3         2021
4         2021
          ...
678945    2021
678946    2021
678947    2021
678948    2021
678949    2021
Name: 대여일자, Length: 678950, dtype: int64

In [25]:
df2['대여일자'].dt.month

0         6
1         6
2         6
3         6
4         6
         ..
678945    6
678946    6
678947    6
678948    6
678949    6
Name: 대여일자, Length: 678950, dtype: int64

In [26]:
df2['대여일자'].dt.day

0          1
1          1
2          1
3          1
4          1
          ..
678945    14
678946    14
678947    14
678948    14
678949    14
Name: 대여일자, Length: 678950, dtype: int64

In [27]:
df2['대여일자'].dt.dayofweek

0         1
1         1
2         1
3         1
4         1
         ..
678945    0
678946    0
678947    0
678948    0
678949    0
Name: 대여일자, Length: 678950, dtype: int64

In [28]:
# 구간 나누기
bins = [0, 6000, 100000, df2['이동거리'].max()]
pd.cut(df2['이동거리'], bins, right=False)

0         [0.0, 6000.0)
1         [0.0, 6000.0)
2         [0.0, 6000.0)
3         [0.0, 6000.0)
4         [0.0, 6000.0)
              ...
678945    [0.0, 6000.0)
678946    [0.0, 6000.0)
678947    [0.0, 6000.0)
678948    [0.0, 6000.0)
678949    [0.0, 6000.0)
Name: 이동거리, Length: 678950, dtype: category
Categories (3, interval[float64, left]): [[0.0, 6000.0) < [6000.0, 100000.0) < [100000.0, 297692.65)]

In [30]:
labels = ['적음', '보통', '많음']
pd.cut(df2['이동거리'], bins, labels=labels, right=False)

0         적음
1         적음
2         적음
3         적음
4         적음
          ..
678945    적음
678946    적음
678947    적음
678948    적음
678949    적음
Name: 이동거리, Length: 678950, dtype: category
Categories (3, object): ['적음' < '보통' < '많음']

In [31]:
df2['이동거리_cut'] = pd.cut(df2['이동거리'], bins=3)
df2['이동거리_cut'].value_counts()

(-297.693, 99230.883]      678948
(198461.767, 297692.65]         2
(99230.883, 198461.767]         0
Name: 이동거리_cut, dtype: int64

In [32]:
df2['이동거리_qcut'] = pd.qcut(df2['이동거리'], q=3)
df2['이동거리_qcut'].value_counts()

(-0.001, 1208.23]       226318
(1208.23, 3008.47]      226317
(3008.47, 297692.65]    226315
Name: 이동거리_qcut, dtype: int64

In [33]:
qcut_bins = [0, 0.2, 0.8, 1]
pd.qcut(df2['이동거리'], qcut_bins)

0            (-0.001, 786.14]
1            (786.14, 4860.0]
2            (786.14, 4860.0]
3            (-0.001, 786.14]
4            (-0.001, 786.14]
                 ...
678945       (786.14, 4860.0]
678946       (-0.001, 786.14]
678947       (786.14, 4860.0]
678948    (4860.0, 297692.65]
678949       (786.14, 4860.0]
Name: 이동거리, Length: 678950, dtype: category
Categories (3, interval[float64, right]): [(-0.001, 786.14] < (786.14, 4860.0] < (4860.0, 297692.65]]

In [34]:
qcut_labels = ['적음', '보통', '많음']
pd.qcut(df2['이동거리'], qcut_bins, labels=qcut_labels).value_counts()

보통    407380
적음    135791
많음    135779
Name: 이동거리, dtype: int64